In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [0]:
dataset = pd.read_csv('dataset.csv')
dataset
X = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values
# print(X)
# print(y)
dataset.shape


(757, 10)

In [0]:
#checking for missing values
dataset.isnull().sum()

Age                           0
BMI                           0
Carbohydrate                  0
Protein                       0
Fat                           0
Water Consumption             0
Foot Steps                    0
Sleep Hours                   0
Diabetes Pedigree Function    0
Output                        0
dtype: int64

In [0]:
#splitting the dataset into training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.25, random_state=0)

In [0]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [0]:
#model fitting
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)  

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
#predicting value
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0])

In [0]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
cm 

array([[104,  19],
       [ 39,  28]])

In [0]:
#Applying K fold cross validation
from sklearn.model_selection import cross_val_score
accuracy= cross_val_score(estimator = classifier, X = X_train, y= y_train, cv = 50)

In [0]:
#Accuracy
accuracy.mean()

0.7042424242424242

In [0]:
#Variance
accuracy.std()

0.09816919110721363

In [0]:
#----------------------------Predicting New values-----------------------# 
#Age : 51 | BMI : 35 | carbo : 40 | protein : 48 | fat : 50 | water consumpation in liters : 4 | footsteps : 8400 |
#sleep hours : 7 | Diabetes Pedigree Function : 0.190
new_prediction= classifier.predict(sc_X.transform(np.array([[51, 35, 40, 48, 50, 4, 8400 , 7, 0.190]])))
new_prediction

array([1])